# coding: utf-8

"""
    Quickpac API

    Here you will find all public interfaces to the Quickpac system.  # noqa: E501

    OpenAPI spec version: v1.00
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.label_data_provider import LabelDataProvider  # noqa: E501
from swagger_client.rest import ApiException


class TestLabelDataProvider(unittest.TestCase):
    """LabelDataProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLabelDataProvider(self):
        """Test LabelDataProvider"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.label_data_provider.LabelDataProvider()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
