# coding: utf-8

# flake8: noqa

"""
    Quickpac API

    Here you will find all public interfaces to the Quickpac system.  # noqa: E501

    OpenAPI spec version: v1.00
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.barcode_api import BarcodeApi
from swagger_client.api.pickup_migros_api import PickupMigrosApi
from swagger_client.api.zip_api import ZIPApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.communication import Communication
from swagger_client.models.dimensions import Dimensions
from swagger_client.models.generate_label_customer import GenerateLabelCustomer
from swagger_client.models.generate_label_definition import GenerateLabelDefinition
from swagger_client.models.generate_label_envelope import GenerateLabelEnvelope
from swagger_client.models.generate_label_file_infos import GenerateLabelFileInfos
from swagger_client.models.generate_label_request import GenerateLabelRequest
from swagger_client.models.generate_label_response import GenerateLabelResponse
from swagger_client.models.generate_label_response_definition import GenerateLabelResponseDefinition
from swagger_client.models.generate_label_response_envelope import GenerateLabelResponseEnvelope
from swagger_client.models.generate_label_response_envelope_data import GenerateLabelResponseEnvelopeData
from swagger_client.models.generate_label_response_envelope_data_provider import GenerateLabelResponseEnvelopeDataProvider
from swagger_client.models.generate_label_response_envelope_data_provider_sending import GenerateLabelResponseEnvelopeDataProviderSending
from swagger_client.models.item import Item
from swagger_client.models.item_choice_type import ItemChoiceType
from swagger_client.models.label_data import LabelData
from swagger_client.models.label_data_provider import LabelDataProvider
from swagger_client.models.label_data_provider_sending import LabelDataProviderSending
from swagger_client.models.label_response_item import LabelResponseItem
from swagger_client.models.language import Language
from swagger_client.models.language_code import LanguageCode
from swagger_client.models.logo_aspect_ratio import LogoAspectRatio
from swagger_client.models.logo_horizontal_align import LogoHorizontalAlign
from swagger_client.models.logo_vertical_align import LogoVerticalAlign
from swagger_client.models.message_type import MessageType
from swagger_client.models.mode_type import ModeType
from swagger_client.models.notification import Notification
from swagger_client.models.notification_type import NotificationType
from swagger_client.models.pickup_migros_callback_result_response import PickupMigrosCallbackResultResponse
from swagger_client.models.pickup_migros_set_paket_status_request import PickupMigrosSetPaketStatusRequest
from swagger_client.models.pickup_migros_set_ruecksendung import PickupMigrosSetRuecksendung
from swagger_client.models.print_addresses_type import PrintAddressesType
from swagger_client.models.recipient import Recipient
from swagger_client.models.service_code_attributes import ServiceCodeAttributes
from swagger_client.models.zip_all_response import ZIPAllResponse
from swagger_client.models.zip_is_current_response import ZIPIsCurrentResponse
from swagger_client.models.zip_model import ZIPModel
